In [1]:
import pandas as pd

In [5]:
df=pd.read_excel('kunnat.xlsx', sheetname='Kuntien avainluvut')
df.head()

,Kunta,"Taajama-aste, %, 2017","Väkiluku, 2017","Väkiluvun muutos edellisestä vuodesta, %, 2017","Alle 15-vuotiaiden osuus väestöstä, %, 2017","15-64 -vuotiaiden osuus väestöstä, %, 2017","Yli 64-vuotiaiden osuus väestöstä, %, 2017","Ruotsinkielisten osuus väestöstä, %, 2017","Ulkomaan kansalaisten osuus väestöstä, %, 2017","Syntyneiden enemmyys, henkilöä, 2017",...,"Taloudellinen huoltosuhde, 2016","Alueella olevien työpaikkojen lukumäärä, 2016","Alkutuotannon työpaikkojen osuus, %, 2016","Jalostuksen työpaikkojen osuus, %, 2016","Palvelujen työpaikkojen osuus, %, 2016","Vuosikate, euroa/asukas, 2017","Lainakanta, euroa/asukas, 2017","Konsernin lainakanta, euroa/asukas, 2017","Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017","Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017"
0,Akaa,88.5,16769,-0.9,18.0,59.8,22.2,0.2,1.6,-47,...,154.2,4512,3.3,35.6,59.5,370.2,3139.1,3927.7,1579.9,3231.2
1,Alajärvi,60.7,9831,-0.7,17.7,55.7,26.6,0.1,1.9,-19,...,187.7,3330,11.6,26.4,59.9,674.0,2152.1,4235.1,2152.6,3579.3
2,Alavieska,52.6,2610,-1.1,19.6,57.3,23.1,0.2,0.6,-5,...,169.3,741,24.4,21.6,52.0,276.2,2988.9,3182.4,1837.5,3995.8
3,Alavus,59.5,11713,-1.6,17.0,56.3,26.6,0.1,1.1,-42,...,172.1,4355,9.9,23.3,65.6,466.4,3307.6,6004.2,1780.8,3886.5
4,Asikkala,64.4,8248,-0.9,14.2,54.7,31.1,0.2,1.6,-51,...,171.7,2318,9.4,27.4,60.8,577.5,1453.7,3014.4,1607.9,3476.6

In [6]:
df.shape

(311, 32)

In [7]:
df.columns

Index(['Kunta', 'Taajama-aste, %, 2017', 'Väkiluku, 2017',
       'Väkiluvun muutos edellisestä vuodesta, %, 2017',
       'Alle 15-vuotiaiden osuus väestöstä, %, 2017',
       '15-64 -vuotiaiden osuus väestöstä, %, 2017',
       'Yli 64-vuotiaiden osuus väestöstä, %, 2017',
       'Ruotsinkielisten osuus väestöstä, %, 2017',
       'Ulkomaan kansalaisten osuus väestöstä, %, 2017',
       'Syntyneiden enemmyys, henkilöä, 2017',
       'Kuntien välinen muuttovoitto/-tappio, henkilöä, 2017',
       'Perheiden lukumäärä, 2017', 'Asuntokuntien lukumäärä, 2017',
       'Rivi- ja pientaloissa asuvien asuntokuntien osuus, %, 2017',
       'Vuokra-asunnoissa asuvien asuntokuntien osuus, %, 2017',
       'Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017',
       'Korkea-asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017',
       'Alueella asuvan työllisen työvoiman määrä, 2016',
       'Työllisyysaste, %, 2016',
       'Asuinkunnassaan työssäkäyvien osuus, %, 2016',
       'Työttömien osuus työvoimasta, %, 2016',
       'Eläkeläisten osuus väestöstä, %, 2016',
       'Taloudellinen huoltosuhde, 2016',
       'Alueella olevien työpaikkojen lukumäärä, 2016',
       'Alkutuotannon työpaikkojen osuus, %, 2016',
       'Jalostuksen työpaikkojen osuus, %, 2016',
       'Palvelujen työpaikkojen osuus, %, 2016',
       'Vuosikate, euroa/asukas, 2017', 'Lainakanta, euroa/asukas, 2017',
       'Konsernin lainakanta, euroa/asukas, 2017',
       'Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017',
       'Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017'],
      dtype='object')

In [8]:
df.count()

Kunta                                                                                     311
Taajama-aste, %, 2017                                                                     311
Väkiluku, 2017                                                                            311
Väkiluvun muutos edellisestä vuodesta, %, 2017                                            311
Alle 15-vuotiaiden osuus väestöstä, %, 2017                                               311
15-64 -vuotiaiden osuus väestöstä, %, 2017                                                311
Yli 64-vuotiaiden osuus väestöstä, %, 2017                                                311
Ruotsinkielisten osuus väestöstä, %, 2017                                                 311
Ulkomaan kansalaisten osuus väestöstä, %, 2017                                            311
Syntyneiden enemmyys, henkilöä, 2017                                                      311
Kuntien välinen muuttovoitto/-tappio, henkilöä, 2017                                      311
Perheiden lukumäärä, 2017                                                                 311
Asuntokuntien lukumäärä, 2017                                                             311
Rivi- ja pientaloissa asuvien asuntokuntien osuus, %, 2017                                311
Vuokra-asunnoissa asuvien asuntokuntien osuus, %, 2017                                    311
Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017    311
Korkea-asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017              311
Alueella asuvan työllisen työvoiman määrä, 2016                                           311
Työllisyysaste, %, 2016                                                                   311
Asuinkunnassaan työssäkäyvien osuus, %, 2016                                              311
Työttömien osuus työvoimasta, %, 2016                                                     311
Eläkeläisten osuus väestöstä, %, 2016                                                     311
Taloudellinen huoltosuhde, 2016                                                           311
Alueella olevien työpaikkojen lukumäärä, 2016                                             311
Alkutuotannon työpaikkojen osuus, %, 2016                                                 311
Jalostuksen työpaikkojen osuus, %, 2016                                                   311
Palvelujen työpaikkojen osuus, %, 2016                                                    311
Vuosikate, euroa/asukas, 2017                                                             311
Lainakanta, euroa/asukas, 2017                                                            311
Konsernin lainakanta, euroa/asukas, 2017                                                  311
Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017        311
Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017        311
dtype: int64

In [10]:
df[df['Väkiluku, 2017']>100000]

,Kunta,"Taajama-aste, %, 2017","Väkiluku, 2017","Väkiluvun muutos edellisestä vuodesta, %, 2017","Alle 15-vuotiaiden osuus väestöstä, %, 2017","15-64 -vuotiaiden osuus väestöstä, %, 2017","Yli 64-vuotiaiden osuus väestöstä, %, 2017","Ruotsinkielisten osuus väestöstä, %, 2017","Ulkomaan kansalaisten osuus väestöstä, %, 2017","Syntyneiden enemmyys, henkilöä, 2017",...,"Taloudellinen huoltosuhde, 2016","Alueella olevien työpaikkojen lukumäärä, 2016","Alkutuotannon työpaikkojen osuus, %, 2016","Jalostuksen työpaikkojen osuus, %, 2016","Palvelujen työpaikkojen osuus, %, 2016","Vuosikate, euroa/asukas, 2017","Lainakanta, euroa/asukas, 2017","Konsernin lainakanta, euroa/asukas, 2017","Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017","Sosiaali- ja terveystoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017"
11,Espoo,99.5,279044,1.6,19.4,66.2,14.5,7.2,10.5,1649,...,115.0,117007,0.1,15.8,82.9,827.6,2887.0,12290.8,2384.0,2574.2
33,Helsinki,100.0,643272,1.3,14.3,68.9,16.8,5.7,9.5,1524,...,111.4,388005,0.1,10.1,88.9,1302.6,1874.7,7749.1,1924.7,2954.5
63,Jyväskylä,94.7,140188,1.0,15.9,66.4,17.7,0.2,3.3,321,...,143.5,60992,0.7,17.7,80.5,478.6,2609.7,7386.3,1711.7,2905.6
114,Kuopio,85.7,118209,0.4,15.0,64.6,20.4,0.1,2.5,-55,...,142.4,50877,2.9,13.9,82.1,486.6,2790.0,8013.1,1894.6,3418.1
123,Lahti,97.4,119573,0.1,14.7,61.8,23.5,0.4,4.3,-181,...,155.7,50483,0.5,24.7,73.8,507.5,6314.3,9182.9,1761.5,3110.6
180,Oulu,96.4,201810,0.6,18.8,65.9,15.3,0.2,2.9,944,...,145.9,85288,0.7,18.9,79.4,590.5,3134.6,4004.1,1941.7,2964.4
268,Tampere,98.6,231853,1.6,13.7,67.5,18.8,0.5,4.6,376,...,138.2,116748,0.2,18.6,80.3,367.1,2276.2,6273.9,2009.8,3245.6
276,Turku,99.0,189669,1.1,12.9,66.7,20.5,5.4,6.5,-10,...,139.9,97273,0.4,16.2,82.4,206.0,3991.5,7296.5,1880.1,3284.9
291,Vantaa,99.7,223027,1.7,17.8,67.0,15.2,2.5,11.2,1149,...,113.1,110784,0.3,21.5,77.4,735.4,4517.0,8836.9,1942.2,2661.7

In [12]:
#nimenvaihto
df.columns=['Kunta', 'Taajama-aste, %, 2017', 'Väkiluku, 2017',
       'Väkiluvun muutos edellisestä vuodesta, %, 2017',
       'Alle 15-vuotiaiden osuus väestöstä, %, 2017',
       '15-64 -vuotiaiden osuus väestöstä, %, 2017',
       'Yli 64-vuotiaiden osuus väestöstä, %, 2017',
       'Ruotsinkielisten osuus väestöstä, %, 2017',
       'Ulkomaan kansalaisten osuus väestöstä, %, 2017',
       'Syntyneiden enemmyys, henkilöä, 2017',
       'Kuntien välinen muuttovoitto/-tappio, henkilöä, 2017',
       'Perheiden lukumäärä, 2017', 'Asuntokuntien lukumäärä, 2017',
       'Rivi- ja pientaloissa asuvien asuntokuntien osuus, %, 2017',
       'Vuokra-asunnoissa asuvien asuntokuntien osuus, %, 2017',
       'Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017',
       'Korkea-asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017',
       'Alueella asuvan työllisen työvoiman määrä, 2016',
       'Työllisyysaste, %, 2016',
       'Asuinkunnassaan työssäkäyvien osuus, %, 2016',
       'Työttömien osuus työvoimasta, %, 2016',
       'Eläkeläisten osuus väestöstä, %, 2016',
       'Taloudellinen huoltosuhde, 2016',
       'Alueella olevien työpaikkojen lukumäärä, 2016',
       'Alkutuotannon työpaikkojen osuus, %, 2016',
       'Jalostuksen työpaikkojen osuus, %, 2016',
       'Palvelujen työpaikkojen osuus, %, 2016',
       'Vuosikate, euroa/asukas, 2017', 'Lainakanta, euroa/asukas, 2017',
       'Konsernin lainakanta, euroa/asukas, 2017',
       'Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017',
       'Sote-toiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017']
df.columns

Index(['Kunta', 'Taajama-aste, %, 2017', 'Väkiluku, 2017',
       'Väkiluvun muutos edellisestä vuodesta, %, 2017',
       'Alle 15-vuotiaiden osuus väestöstä, %, 2017',
       '15-64 -vuotiaiden osuus väestöstä, %, 2017',
       'Yli 64-vuotiaiden osuus väestöstä, %, 2017',
       'Ruotsinkielisten osuus väestöstä, %, 2017',
       'Ulkomaan kansalaisten osuus väestöstä, %, 2017',
       'Syntyneiden enemmyys, henkilöä, 2017',
       'Kuntien välinen muuttovoitto/-tappio, henkilöä, 2017',
       'Perheiden lukumäärä, 2017', 'Asuntokuntien lukumäärä, 2017',
       'Rivi- ja pientaloissa asuvien asuntokuntien osuus, %, 2017',
       'Vuokra-asunnoissa asuvien asuntokuntien osuus, %, 2017',
       'Vähintään toisen asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017',
       'Korkea-asteen tutkinnon suorittaneiden osuus 15 vuotta täyttäneistä, %, 2017',
       'Alueella asuvan työllisen työvoiman määrä, 2016',
       'Työllisyysaste, %, 2016',
       'Asuinkunnassaan työssäkäyvien osuus, %, 2016',
       'Työttömien osuus työvoimasta, %, 2016',
       'Eläkeläisten osuus väestöstä, %, 2016',
       'Taloudellinen huoltosuhde, 2016',
       'Alueella olevien työpaikkojen lukumäärä, 2016',
       'Alkutuotannon työpaikkojen osuus, %, 2016',
       'Jalostuksen työpaikkojen osuus, %, 2016',
       'Palvelujen työpaikkojen osuus, %, 2016',
       'Vuosikate, euroa/asukas, 2017', 'Lainakanta, euroa/asukas, 2017',
       'Konsernin lainakanta, euroa/asukas, 2017',
       'Opetus- ja kulttuuritoiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017',
       'Sote-toiminta yhteensä, nettokäyttökustannukset, euroa/asukas, 2017'],
      dtype='object')

In [14]:
df[['Kunta','Alkutuotannon työpaikkojen osuus, %, 2016','Jalostuksen työpaikkojen osuus, %, 2016','Palvelujen työpaikkojen osuus, %, 2016']].sort_values(by='Alkutuotannon työpaikkojen osuus, %, 2016', ascending=False).head(10)

,Kunta,"Alkutuotannon työpaikkojen osuus, %, 2016","Jalostuksen työpaikkojen osuus, %, 2016","Palvelujen työpaikkojen osuus, %, 2016"
136,Lestijärvi,43.3,14.2,40.5
242,Savukoski,42.4,3.3,53.0
303,Vårdö,38.2,14.6,39.0
257,Sottunga,35.7,7.1,57.1
22,Halsua,30.1,22.7,45.0
36,Honkajoki,29.1,26.3,42.5
76,Karijoki,28.4,27.0,42.7
64,Jämijärvi,28.3,24.3,44.3
220,Rantasalmi,28.0,18.4,52.1
233,Rääkkylä,27.3,13.3,56.1

In [15]:
df[['Kunta','Alkutuotannon työpaikkojen osuus, %, 2016','Jalostuksen työpaikkojen osuus, %, 2016','Palvelujen työpaikkojen osuus, %, 2016']].sort_values(by='Palvelujen työpaikkojen osuus, %, 2016', ascending=False).head(10)

,Kunta,"Alkutuotannon työpaikkojen osuus, %, 2016","Jalostuksen työpaikkojen osuus, %, 2016","Palvelujen työpaikkojen osuus, %, 2016"
83,Kauniainen,0.5,3.1,93.4
160,Muonio,2.3,6.6,89.4
151,Maarianhamina,0.2,9.0,88.9
33,Helsinki,0.1,10.1,88.9
50,Inari,6.4,6.7,84.7
189,Pelkosenniemi,4.9,9.7,84.4
229,Rovaniemi,2.2,13.0,83.5
11,Espoo,0.1,15.8,82.9
276,Turku,0.4,16.2,82.4
102,Kolari,4.1,9.5,82.1

In [21]:
df[['Kunta','Työllisyysaste, %, 2016','Eläkeläisten osuus väestöstä, %, 2016','Ruotsinkielisten osuus väestöstä, %, 2017','Taloudellinen huoltosuhde, 2016']][df['Taloudellinen huoltosuhde, 2016']<100]

,Kunta,"Työllisyysaste, %, 2016","Eläkeläisten osuus väestöstä, %, 2016","Ruotsinkielisten osuus väestöstä, %, 2017","Taloudellinen huoltosuhde, 2016"
57,Jomala,87.5,15.8,89.1,86.8
133,Lemland,84.3,18.2,92.1,96.5
257,Sottunga,89.5,37.5,93.5,84.6
259,Sund,86.3,25.2,88.8,97.6